version: '3'
services:
    # mssql docker
    medlabo-sql:
        image: mcr.microsoft.com/mssql/server:2017-latest-ubuntu
        restart: unless-stopped
        environment:
            - ACCEPT_EULA=Y
            - SA_PASSWORD=medlabo123
            - MSSQL_PID=Developer
        ports:
            - 1401:1433
        expose:
            - 1433
        networks:
            - medlabonet2023
            
    rabbitmq:
        image: rabbitmq:3-management
        container_name: rabbitmq
        restart: unless-stopped
        environment:
            - RABBITMQ_DEFAULT_USER=guest
            - RABBITMQ_DEFAULT_PASS=guest
        ports:
            - "5672:5672"
            - "15672:15672"
        expose:
            - 5672
        networks:
            - medlabonet2023
            
    emailnotification:
        build:
            context: .
            dockerfile: Dockerfile.emailnotifier
        environment:
            - RABBITMQ_HOSTNAME=rabbitmq
            - RABBITMQ_VIRTUALHOST=/
            - RABBITMQ_USERNAME=guest
            - RABBITMQ_PASSWORD=guest
            - OUTLOOK_EMAIL=medlabonline@outlook.com
            - OUTLOOK_PASSWORD=MedLabO100123
        depends_on:
            - rabbitmq
            - medlabo-api
        networks:
            - medlabonet2023
        ports:
            - 7101:80
    
    medlabo-api:
        restart: unless-stopped
        build:
            context: .
        environment:
            - ConnectionStrings:MedLabOContextConnectionString=Server=medlabo-sql,1433;Database=200204;User Id=sa;Password=medlabo123;TrustServerCertificate=True;MultipleActiveResultSets=True
            - ASPNETCORE_ENVIRONMENT=Development
            - RABBITMQ_HOSTNAME=rabbitmq
            - RABBITMQ_USERNAME=guest
            - RABBITMQ_PASSWORD=guest
            - RABBITMQ_VIRTUALHOST=/
        ports:
            - 7213:7213
        networks:
            - medlabonet2023
        links:
            - medlabo-sql
        depends_on:
            - medlabo-sql
            - rabbitmq
             
networks:
    medlabonet2023:
        driver: bridge