// <auto-generated />
using System;
using MedLabO.Services.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MedLabO.Services.Migrations
{
    [DbContext(typeof(MedLabOContext))]
    [Migration("20231216230430_init")]
    partial class init
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.15")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("MedLabO.Services.Database.ApplicationUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("isDeleted")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);

                    b.HasDiscriminator<string>("Discriminator").HasValue("ApplicationUser");
                });

            modelBuilder.Entity("MedLabO.Services.Database.Novost", b =>
                {
                    b.Property<Guid>("NovostID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("AdministratorID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("DTKreiranja")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DTZadnjeModifikacije")
                        .HasColumnType("datetime2");

                    b.Property<string>("Naslov")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Sadrzaj")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte[]>("Slika")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.HasKey("NovostID");

                    b.HasIndex("AdministratorID");

                    b.ToTable("Novosti");

                    b.HasData(
                        new
                        {
                            NovostID = new Guid("fc31fac7-27e4-41bd-95f4-da76a956bd23"),
                            AdministratorID = new Guid("e6bb3c49-9aa6-4ef0-9625-b16bb3775e58"),
                            DTKreiranja = new DateTime(2023, 12, 17, 0, 4, 29, 273, DateTimeKind.Local).AddTicks(5960),
                            Naslov = "Novi Testovi Dostupni u Našem Laboratoriju",
                            Sadrzaj = "Dragi pacijenti, s ponosom vas obavještavamo da smo proširili našu ponudu testova. Novi testovi uključuju napredne genetske analize, testove intolerancije na hranu, i detaljne hormonalne profile. Ovi testovi su dizajnirani da vam pruže dublji uvid u vaše zdravstveno stanje i omoguće personalizirani pristup liječenju. Naš tim stručnjaka je na raspolaganju da odgovori na sva vaša pitanja i pomogne vam odabrati najprikladnije testove za vaše potrebe. Posjetite nas i saznajte više o novim mogućnostima koje vam nudimo za očuvanje i unapređenje vašeg zdravlja.",
                            Slika = new byte[0]
                        },
                        new
                        {
                            NovostID = new Guid("be49f5ad-6d18-435e-97a5-13600af6b4e5"),
                            AdministratorID = new Guid("e6bb3c49-9aa6-4ef0-9625-b16bb3775e58"),
                            DTKreiranja = new DateTime(2023, 12, 17, 0, 4, 29, 273, DateTimeKind.Local).AddTicks(5978),
                            Naslov = "Dan Otvorenih Vrata u Laboratoriju",
                            Sadrzaj = "Pozivamo vas na Dan otvorenih vrata koji će se održati 15.04.2023. u našem laboratoriju. Ovo je izvrsna prilika da se upoznate s našim radom, tehnologijama koje koristimo i timom stručnjaka koji brinu o vašem zdravlju. Tijekom ovog dana, moći ćete besplatno izvršiti osnovne zdravstvene preglede, sudjelovati u edukativnim radionicama i dobiti individualne savjete o zdravlju. Također, pripremili smo posebne popuste na odabrane testove i usluge. Ne propustite ovu priliku da saznate više o važnosti preventivnih pregleda i kako možete aktivno doprinijeti očuvanju svog zdravlja.",
                            Slika = new byte[0]
                        },
                        new
                        {
                            NovostID = new Guid("465a1478-3027-498f-aa82-b46b9a0ec4ee"),
                            AdministratorID = new Guid("e6bb3c49-9aa6-4ef0-9625-b16bb3775e58"),
                            DTKreiranja = new DateTime(2023, 12, 17, 0, 4, 29, 273, DateTimeKind.Local).AddTicks(5995),
                            Naslov = "Obavijest o Radnom Vremenu za Praznike",
                            Sadrzaj = "Obavještavamo naše cijenjene pacijente da će tijekom nadolazećih praznika doći do promjena u radnom vremenu našeg laboratorija. Na Badnjak i Staru godinu laboratorij će raditi skraćeno, do 12:00 sati, dok će na Božić i Novu godinu laboratorij biti zatvoren. Molimo vas da planirate svoje posjete i testiranja sukladno ovom rasporedu. Također, želimo iskoristiti ovu priliku da vam zaželimo sretne i mirne praznike. Neka ovo vrijeme bude ispunjeno zdravljem, srećom i radosti. U novoj godini nastavljamo s našom misijom pružanja vrhunske zdravstvene skrbi i usluga. Hvala vam što ste dio naše zajednice i što nam vjerujete brigu o vašem zdravlju.",
                            Slika = new byte[0]
                        },
                        new
                        {
                            NovostID = new Guid("325d2b08-9822-4ef1-acbd-2d4528bbeebc"),
                            AdministratorID = new Guid("e6bb3c49-9aa6-4ef0-9625-b16bb3775e58"),
                            DTKreiranja = new DateTime(2023, 12, 17, 0, 4, 29, 273, DateTimeKind.Local).AddTicks(6018),
                            Naslov = "Uvođenje Online Rezervacija Termina",
                            Sadrzaj = "S ciljem poboljšanja naših usluga i olakšavanja pristupa zdravstvenoj skrbi, uvodimo novi sustav online rezervacija termina putem naše web stranice. Od sada, možete jednostavno i brzo rezervirati svoj termin za testiranje također putem naše web stranice. Ovaj sustav omogućava vam da izaberete datum i vrijeme koje vam najviše odgovara, bez potrebe za čekanjem u redu ili telefonskim pozivima. Također, putem sustava možete pratiti svoje rezervacije, dobiti podsjetnike za nadolazeće termine i pristupiti rezultatima testiranja. Naš cilj je učiniti proces testiranja što jednostavnijim i ugodnijim za vas, te vam pružiti brz i efikasan pristup informacijama o vašem zdravlju. Pozivamo vas da isprobate naš novi sustav rezervacija i podijelite s nama svoje dojmove.",
                            Slika = new byte[0]
                        },
                        new
                        {
                            NovostID = new Guid("7fa51a3e-501c-4466-90e2-1eba0a549d23"),
                            AdministratorID = new Guid("e6bb3c49-9aa6-4ef0-9625-b16bb3775e58"),
                            DTKreiranja = new DateTime(2023, 12, 17, 0, 4, 29, 273, DateTimeKind.Local).AddTicks(6044),
                            Naslov = "Modernizacija Laboratorijske Opreme",
                            Sadrzaj = "S ponosom vas obavještavamo o nedavnoj modernizaciji naše laboratorijske opreme. Ulaganjem u najnovije tehnologije, osigurali smo da naši pacijenti imaju pristup najpreciznijim i najbržim dijagnostičkim testovima. Nova oprema omogućava nam da proširimo spektar testova, smanjimo vrijeme čekanja na rezultate i povećamo tačnost dijagnostike. Ovo je važan korak u našem nastojanju da pružimo vrhunsku medicinsku skrb i podršku našim pacijentima. Vjerujemo da će ove promjene značajno doprinijeti kvaliteti i efikasnosti naših usluga, te vam omogućiti bolje upravljanje vašim zdravljem. Zahvaljujemo vam na povjerenju i radujemo se što ćemo vam pružiti još bolju uslugu uz pomoć ove napredne tehnologije.",
                            Slika = new byte[0]
                        });
                });

            modelBuilder.Entity("MedLabO.Services.Database.Obavijest", b =>
                {
                    b.Property<Guid>("ObavijestID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("AdministratorID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("DTKreiranja")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DTZadnjeModifikacije")
                        .HasColumnType("datetime2");

                    b.Property<string>("Naslov")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Sadrzaj")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte[]>("Slika")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.HasKey("ObavijestID");

                    b.HasIndex("AdministratorID");

                    b.ToTable("Obavijesti");

                    b.HasData(
                        new
                        {
                            ObavijestID = new Guid("0e322352-b209-4dce-8369-9d7d67f38daf"),
                            AdministratorID = new Guid("e6bb3c49-9aa6-4ef0-9625-b16bb3775e58"),
                            DTKreiranja = new DateTime(2023, 12, 17, 0, 4, 29, 273, DateTimeKind.Local).AddTicks(5849),
                            Naslov = "Neradni Dan - 18.02.2023.",
                            Sadrzaj = "Poštovani kolege, obavještavamo vas da će laboratorij biti zatvoren 18.02.2023. zbog redovnog godišnjeg održavanja opreme i prostorija. Ovo je idealna prilika da se posvetite svom zdravlju i porodici, te da napunite baterije za nove radne izazove. Molimo vas da sve planirane aktivnosti prilagodite ovom datumu. Također, podsjećamo vas da je važno redovno pratiti stanje i održavanje opreme, kako bismo osigurali najviši standard naših usluga. Hvala vam na razumijevanju i suradnji.",
                            Slika = new byte[0]
                        },
                        new
                        {
                            ObavijestID = new Guid("55d8e97e-4379-4978-940a-d342158c5ce5"),
                            AdministratorID = new Guid("e6bb3c49-9aa6-4ef0-9625-b16bb3775e58"),
                            DTKreiranja = new DateTime(2023, 12, 17, 0, 4, 29, 273, DateTimeKind.Local).AddTicks(5884),
                            Naslov = "Edukacijski Seminar za Zaposlenike",
                            Sadrzaj = "Drage kolege, s velikim zadovoljstvom vas obavještavamo da ćemo 25.03.2023. organizirati edukacijski seminar na temu \"Najnovije tehnike u laboratorijskim ispitivanjima\". Seminar će voditi priznati stručnjaci u našem području rada. Ovo je izvrsna prilika za usavršavanje i razmjenu iskustava s kolegama iz struke. Seminar će se održati u konferencijskoj sali našeg laboratorija, s početkom u 10:00 sati. Molimo sve zainteresirane da potvrde svoje sudjelovanje najkasnije do 15.03.2023.",
                            Slika = new byte[0]
                        },
                        new
                        {
                            ObavijestID = new Guid("04cf6396-4405-43b0-87bc-fee864a88e2e"),
                            AdministratorID = new Guid("e6bb3c49-9aa6-4ef0-9625-b16bb3775e58"),
                            DTKreiranja = new DateTime(2023, 12, 17, 0, 4, 29, 273, DateTimeKind.Local).AddTicks(5900),
                            Naslov = "Promjena Protokola za Obradu Uzoraka",
                            Sadrzaj = "Obavještavamo sve zaposlenike da od 01.04.2023. stupaju na snagu novi protokoli za obradu uzoraka. Novi protokoli uključuju ažurirane postupke za rukovanje, analizu i pohranu uzoraka, s ciljem povećanja efikasnosti i tačnosti naših testova. Detaljne upute i obuke bit će organizirane u narednim sedmicama. Molimo sve zaposlenike da se upoznaju s novim protokolima i prate upute za obuku. Vaša suradnja i pridržavanje novih protokola su ključni za uspjeh ove promjene.",
                            Slika = new byte[0]
                        },
                        new
                        {
                            ObavijestID = new Guid("af32cfec-6818-44f2-9efa-053d24bebd9d"),
                            AdministratorID = new Guid("e6bb3c49-9aa6-4ef0-9625-b16bb3775e58"),
                            DTKreiranja = new DateTime(2023, 12, 17, 0, 4, 29, 273, DateTimeKind.Local).AddTicks(5915),
                            Naslov = "Godišnji Plan Odmora",
                            Sadrzaj = "Kako bismo osigurali kontinuirani rad laboratorija i zadovoljili potrebe naših pacijenata, molimo sve zaposlenike da do 15.04.2023. dostave svoje planove godišnjih odmora. Važno je da planiramo i koordiniramo odmore kako bismo izbjegli preklapanja i osigurali adekvatno osoblje u svakom trenutku. Molimo vas da razmotrite potrebe vašeg tima i laboratorija prilikom planiranja odmora. U slučaju bilo kakvih pitanja ili nedoumica, slobodno se obratite odjelu ljudskih resursa.",
                            Slika = new byte[0]
                        },
                        new
                        {
                            ObavijestID = new Guid("6cb8671d-2034-4bed-9a8b-1cf5a2f4d917"),
                            AdministratorID = new Guid("e6bb3c49-9aa6-4ef0-9625-b16bb3775e58"),
                            DTKreiranja = new DateTime(2023, 12, 17, 0, 4, 29, 273, DateTimeKind.Local).AddTicks(5931),
                            Naslov = "Sigurnosne Mjere u Laboratoriju",
                            Sadrzaj = "Sigurnost na radnom mjestu je naš prioritet. Stoga vas podsjećamo na važnost pridržavanja svih sigurnosnih protokola i procedura u laboratoriju. Ovo uključuje pravilno nošenje zaštitne opreme, pažljivo rukovanje uzorcima i hemikalijama, te održavanje čistoće i urednosti radnog prostora. Redovite provjere i obuke o sigurnosti bit će organizirane kako bismo osigurali da su svi upoznati s najboljim praksama i procedurama. Vaša sigurnost i zdravlje su od izuzetne važnosti, stoga vas molimo da ozbiljno shvatite ove mjere.",
                            Slika = new byte[0]
                        });
                });

            modelBuilder.Entity("MedLabO.Services.Database.Racun", b =>
                {
                    b.Property<Guid>("RacunID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("Cijena")
                        .HasColumnType("decimal(18,2)");

                    b.Property<bool>("Placeno")
                        .HasColumnType("bit");

                    b.Property<Guid?>("TerminID")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("RacunID");

                    b.HasIndex("TerminID");

                    b.ToTable("Racuni");
                });

            modelBuilder.Entity("MedLabO.Services.Database.Rezultat", b =>
                {
                    b.Property<Guid>("RezultatID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("DTRezultata")
                        .HasColumnType("datetime2");

                    b.Property<bool>("Obiljezen")
                        .HasColumnType("bit");

                    b.Property<float?>("RazlikaOdNormalne")
                        .HasColumnType("real");

                    b.Property<float?>("RezFlo")
                        .HasColumnType("real");

                    b.Property<string>("RezStr")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TestZakljucak")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("RezultatID");

                    b.ToTable("Rezultati");
                });

            modelBuilder.Entity("MedLabO.Services.Database.Spol", b =>
                {
                    b.Property<int>("SpolID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SpolID"), 1L, 1);

                    b.Property<string>("Kod")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Naziv")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("SpolID");

                    b.ToTable("Spolovi");

                    b.HasData(
                        new
                        {
                            SpolID = 1,
                            Kod = "M",
                            Naziv = "Muško"
                        },
                        new
                        {
                            SpolID = 2,
                            Kod = "Ž",
                            Naziv = "Žensko"
                        },
                        new
                        {
                            SpolID = 3,
                            Kod = "N",
                            Naziv = "Nepoznato"
                        });
                });

            modelBuilder.Entity("MedLabO.Services.Database.Termin", b =>
                {
                    b.Property<Guid>("TerminID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("DTTermina")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("MedicinskoOsobljeID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Napomena")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<bool>("Obavljen")
                        .HasColumnType("bit");

                    b.Property<string>("Odgovor")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<Guid?>("PacijentID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Placeno")
                        .HasColumnType("bit");

                    b.Property<Guid?>("RacunID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("RazlogOtkazivanja")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<bool>("RezultatDodan")
                        .HasColumnType("bit");

                    b.Property<byte[]>("RezultatTerminaPDF")
                        .HasColumnType("varbinary(max)");

                    b.Property<bool?>("Status")
                        .HasColumnType("bit");

                    b.Property<bool>("ZakljucakDodan")
                        .HasColumnType("bit");

                    b.Property<Guid?>("ZakljucakID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("isDeleted")
                        .HasColumnType("bit");

                    b.HasKey("TerminID");

                    b.HasIndex("MedicinskoOsobljeID");

                    b.HasIndex("PacijentID");

                    b.HasIndex("RacunID");

                    b.HasIndex("ZakljucakID");

                    b.ToTable("Termini");
                });

            modelBuilder.Entity("MedLabO.Services.Database.TerminTest", b =>
                {
                    b.Property<Guid?>("TestID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("TerminID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("RezultatID")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("TestID", "TerminID");

                    b.HasIndex("RezultatID");

                    b.HasIndex("TerminID");

                    b.ToTable("TerminTest");
                });

            modelBuilder.Entity("MedLabO.Services.Database.Test", b =>
                {
                    b.Property<Guid>("TestID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("AdministratorID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("Cijena")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("DTKreiranja")
                        .HasColumnType("datetime2");

                    b.Property<string>("NapomenaZaPripremu")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Naziv")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Opis")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte[]>("Slika")
                        .HasColumnType("varbinary(max)");

                    b.Property<Guid?>("TestParametarID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("TipUzorka")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("TestID");

                    b.HasIndex("AdministratorID");

                    b.HasIndex("TestParametarID");

                    b.ToTable("Testovi");

                    b.HasData(
                        new
                        {
                            TestID = new Guid("d687ff9d-1ec4-4aa9-a4f3-2eb5149d2212"),
                            AdministratorID = new Guid("e6bb3c49-9aa6-4ef0-9625-b16bb3775e58"),
                            Cijena = 2m,
                            DTKreiranja = new DateTime(2023, 12, 17, 0, 4, 29, 273, DateTimeKind.Local).AddTicks(5083),
                            NapomenaZaPripremu = "Post od 8 sati prije testa.",
                            Naziv = "Glukoza",
                            Opis = "Mjerenje glukoze u krvi, važno za dijagnozu i praćenje dijabetesa.",
                            Slika = new byte[0],
                            TestParametarID = new Guid("46cba49e-0b4b-4018-ae70-5c9ceae529b5"),
                            TipUzorka = "Krv"
                        },
                        new
                        {
                            TestID = new Guid("8fff236b-4a25-4ed3-a138-f252ee4770eb"),
                            AdministratorID = new Guid("e6bb3c49-9aa6-4ef0-9625-b16bb3775e58"),
                            Cijena = 2.5m,
                            DTKreiranja = new DateTime(2023, 12, 17, 0, 4, 29, 273, DateTimeKind.Local).AddTicks(5120),
                            NapomenaZaPripremu = "Nema posebnih uputa.",
                            Naziv = "Leukociti",
                            Opis = "Broj leukocita, važan za otkrivanje infekcija ili upalnih procesa.",
                            Slika = new byte[0],
                            TestParametarID = new Guid("d70a4bfa-38c0-4d41-a090-208404e57209"),
                            TipUzorka = "Krv"
                        },
                        new
                        {
                            TestID = new Guid("54d120fc-224a-4710-9046-162d9b61c2d7"),
                            AdministratorID = new Guid("e6bb3c49-9aa6-4ef0-9625-b16bb3775e58"),
                            Cijena = 2.5m,
                            DTKreiranja = new DateTime(2023, 12, 17, 0, 4, 29, 273, DateTimeKind.Local).AddTicks(5150),
                            NapomenaZaPripremu = "Nema posebnih uputa.",
                            Naziv = "Eritrociti",
                            Opis = "Broj eritrocita, važan za dijagnozu anemije i drugih poremećaja.",
                            Slika = new byte[0],
                            TestParametarID = new Guid("bab9d588-8ff1-4355-96fd-f94d9bdb4a8d"),
                            TipUzorka = "Krv"
                        },
                        new
                        {
                            TestID = new Guid("ef16a7e3-3117-4246-ae58-fc54d2307c77"),
                            AdministratorID = new Guid("e6bb3c49-9aa6-4ef0-9625-b16bb3775e58"),
                            Cijena = 3m,
                            DTKreiranja = new DateTime(2023, 12, 17, 0, 4, 29, 273, DateTimeKind.Local).AddTicks(5177),
                            NapomenaZaPripremu = "Nema posebnih uputa.",
                            Naziv = "MCHC",
                            Opis = "Prosječna koncentracija hemoglobina u eritrocitu.",
                            Slika = new byte[0],
                            TestParametarID = new Guid("e8319b5a-0868-4fef-b356-32f9fdabbd82"),
                            TipUzorka = "Krv"
                        },
                        new
                        {
                            TestID = new Guid("ad25cc31-2b01-4ad3-bf2e-1fe4b53a3f25"),
                            AdministratorID = new Guid("e6bb3c49-9aa6-4ef0-9625-b16bb3775e58"),
                            Cijena = 3m,
                            DTKreiranja = new DateTime(2023, 12, 17, 0, 4, 29, 273, DateTimeKind.Local).AddTicks(5211),
                            NapomenaZaPripremu = "Nema posebnih uputa.",
                            Naziv = "AST",
                            Opis = "Enzim važan za otkrivanje oštećenja jetre.",
                            Slika = new byte[0],
                            TestParametarID = new Guid("901a4f75-3529-4b57-b9c0-8dd99f495d32"),
                            TipUzorka = "Krv"
                        },
                        new
                        {
                            TestID = new Guid("a4a12d1c-b174-4938-8557-cb6281ccb2a6"),
                            AdministratorID = new Guid("e6bb3c49-9aa6-4ef0-9625-b16bb3775e58"),
                            Cijena = 2m,
                            DTKreiranja = new DateTime(2023, 12, 17, 0, 4, 29, 273, DateTimeKind.Local).AddTicks(5240),
                            NapomenaZaPripremu = "Nema posebnih uputa.",
                            Naziv = "Sedimentacija",
                            Opis = "Brzina sedimentacije eritrocita, indikator upalnih procesa.",
                            Slika = new byte[0],
                            TestParametarID = new Guid("788e2d86-4fc5-49a8-994e-541180dba9bb"),
                            TipUzorka = "Krv"
                        },
                        new
                        {
                            TestID = new Guid("0c1a4613-be50-48a6-abcb-a535870fe369"),
                            AdministratorID = new Guid("e6bb3c49-9aa6-4ef0-9625-b16bb3775e58"),
                            Cijena = 3.5m,
                            DTKreiranja = new DateTime(2023, 12, 17, 0, 4, 29, 273, DateTimeKind.Local).AddTicks(5277),
                            NapomenaZaPripremu = "Nema posebnih uputa.",
                            Naziv = "CRP",
                            Opis = "Marker za upalu u tijelu.",
                            Slika = new byte[0],
                            TestParametarID = new Guid("0fe0697a-aa20-4e20-b152-58f6ed44efc3"),
                            TipUzorka = "Krv"
                        },
                        new
                        {
                            TestID = new Guid("14a35eb5-c4bd-4a0b-9990-c8b493367bcf"),
                            AdministratorID = new Guid("e6bb3c49-9aa6-4ef0-9625-b16bb3775e58"),
                            Cijena = 3m,
                            DTKreiranja = new DateTime(2023, 12, 17, 0, 4, 29, 273, DateTimeKind.Local).AddTicks(5306),
                            NapomenaZaPripremu = "Nema posebnih uputa.",
                            Naziv = "Bilirubin",
                            Opis = "Mjerenje bilirubina, važno za otkrivanje bolesti jetre i žučnih puteva.",
                            Slika = new byte[0],
                            TestParametarID = new Guid("77886ff8-caf5-4247-ae64-62e1a8c0969f"),
                            TipUzorka = "Krv"
                        },
                        new
                        {
                            TestID = new Guid("1c978bd5-9777-4c05-b2ae-de4d3b9b4fc5"),
                            AdministratorID = new Guid("e6bb3c49-9aa6-4ef0-9625-b16bb3775e58"),
                            Cijena = 2.5m,
                            DTKreiranja = new DateTime(2023, 12, 17, 0, 4, 29, 273, DateTimeKind.Local).AddTicks(5340),
                            NapomenaZaPripremu = "Post od 12 sati prije testa.",
                            Naziv = "Holesterol",
                            Opis = "Mjerenje ukupnog holesterola, važno za procjenu rizika od kardiovaskularnih bolesti.",
                            Slika = new byte[0],
                            TestParametarID = new Guid("e8e1e4b9-7fe9-4015-9f62-f3c844e831ce"),
                            TipUzorka = "Krv"
                        },
                        new
                        {
                            TestID = new Guid("20b1bda2-14bc-4b3f-bac4-598e2a292519"),
                            AdministratorID = new Guid("e6bb3c49-9aa6-4ef0-9625-b16bb3775e58"),
                            Cijena = 2.5m,
                            DTKreiranja = new DateTime(2023, 12, 17, 0, 4, 29, 273, DateTimeKind.Local).AddTicks(5395),
                            NapomenaZaPripremu = "Post od 12 sati prije testa.",
                            Naziv = "Trigliceridi",
                            Opis = "Mjerenje triglicerida, važno za procjenu rizika od srčanih bolesti.",
                            Slika = new byte[0],
                            TestParametarID = new Guid("e4f11b51-c4e6-473d-9221-c617354745f3"),
                            TipUzorka = "Krv"
                        },
                        new
                        {
                            TestID = new Guid("0c9db61b-d5e5-495d-876b-30ad80a8df3d"),
                            AdministratorID = new Guid("e6bb3c49-9aa6-4ef0-9625-b16bb3775e58"),
                            Cijena = 4.5m,
                            DTKreiranja = new DateTime(2023, 12, 17, 0, 4, 29, 273, DateTimeKind.Local).AddTicks(5469),
                            NapomenaZaPripremu = "Jutarnji sputum.",
                            Naziv = "Citologija sputuma",
                            Opis = "Analiza sputuma za otkrivanje abnormalnih stanica.",
                            Slika = new byte[0],
                            TestParametarID = new Guid("75b1dbb5-6b3c-4c76-8044-caff96608e08"),
                            TipUzorka = "Sputum"
                        },
                        new
                        {
                            TestID = new Guid("59a5aaae-ec61-476d-84f5-2621d4054160"),
                            AdministratorID = new Guid("e6bb3c49-9aa6-4ef0-9625-b16bb3775e58"),
                            Cijena = 5m,
                            DTKreiranja = new DateTime(2023, 12, 17, 0, 4, 29, 273, DateTimeKind.Local).AddTicks(5538),
                            NapomenaZaPripremu = "Nema posebnih uputa.",
                            Naziv = "Nasalni bris za MRSA",
                            Opis = "Testiranje na prisutnost MRSA (meticilin-rezistentni Staphylococcus aureus) u nosnoj šupljini.",
                            Slika = new byte[0],
                            TestParametarID = new Guid("84bfaf38-20b5-4648-b8f0-9d2c4cf7b95a"),
                            TipUzorka = "Nasalni bris"
                        },
                        new
                        {
                            TestID = new Guid("d9f7156c-a460-4a7c-b51c-ef7d859244af"),
                            AdministratorID = new Guid("e6bb3c49-9aa6-4ef0-9625-b16bb3775e58"),
                            Cijena = 3m,
                            DTKreiranja = new DateTime(2023, 12, 17, 0, 4, 29, 273, DateTimeKind.Local).AddTicks(5575),
                            NapomenaZaPripremu = "Jutarnji urin.",
                            Naziv = "Urinarni albumin",
                            Opis = "Mjerenje albumina u urinu, indikator oštećenja bubrega.",
                            Slika = new byte[0],
                            TestParametarID = new Guid("e16fecb2-a4cf-41fd-a264-18dbc8a25cc8"),
                            TipUzorka = "Urin"
                        });
                });

            modelBuilder.Entity("MedLabO.Services.Database.TestParametar", b =>
                {
                    b.Property<Guid>("TestParametarID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Jedinica")
                        .HasColumnType("nvarchar(max)");

                    b.Property<float?>("MaxVrijednost")
                        .HasColumnType("real");

                    b.Property<float?>("MinVrijednost")
                        .HasColumnType("real");

                    b.Property<string>("NormalnaVrijednost")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("TestParametarID");

                    b.ToTable("TestParametri");

                    b.HasData(
                        new
                        {
                            TestParametarID = new Guid("46cba49e-0b4b-4018-ae70-5c9ceae529b5"),
                            Jedinica = "mmol/L",
                            MaxVrijednost = 5.8f,
                            MinVrijednost = 3.9f
                        },
                        new
                        {
                            TestParametarID = new Guid("d70a4bfa-38c0-4d41-a090-208404e57209"),
                            Jedinica = "x10^9/L",
                            MaxVrijednost = 11f,
                            MinVrijednost = 4f
                        },
                        new
                        {
                            TestParametarID = new Guid("bab9d588-8ff1-4355-96fd-f94d9bdb4a8d"),
                            Jedinica = "x10^12/L",
                            MaxVrijednost = 5.9f,
                            MinVrijednost = 3.8f
                        },
                        new
                        {
                            TestParametarID = new Guid("e8319b5a-0868-4fef-b356-32f9fdabbd82"),
                            Jedinica = "g/L",
                            MaxVrijednost = 355f,
                            MinVrijednost = 320f
                        },
                        new
                        {
                            TestParametarID = new Guid("901a4f75-3529-4b57-b9c0-8dd99f495d32"),
                            Jedinica = "U/L",
                            MaxVrijednost = 40f,
                            MinVrijednost = 0f
                        },
                        new
                        {
                            TestParametarID = new Guid("788e2d86-4fc5-49a8-994e-541180dba9bb"),
                            Jedinica = "mm/h",
                            MaxVrijednost = 30f,
                            MinVrijednost = 0f
                        },
                        new
                        {
                            TestParametarID = new Guid("0fe0697a-aa20-4e20-b152-58f6ed44efc3"),
                            Jedinica = "mg/L",
                            MaxVrijednost = 5f,
                            MinVrijednost = 0f
                        },
                        new
                        {
                            TestParametarID = new Guid("77886ff8-caf5-4247-ae64-62e1a8c0969f"),
                            Jedinica = "mg/dL",
                            MaxVrijednost = 20.5f,
                            MinVrijednost = 1.2f
                        },
                        new
                        {
                            TestParametarID = new Guid("e8e1e4b9-7fe9-4015-9f62-f3c844e831ce"),
                            Jedinica = "mmol/L",
                            MaxVrijednost = 7.8f,
                            MinVrijednost = 3.6f
                        },
                        new
                        {
                            TestParametarID = new Guid("e4f11b51-c4e6-473d-9221-c617354745f3"),
                            Jedinica = "mmol/L",
                            MaxVrijednost = 2.3f,
                            MinVrijednost = 0f
                        },
                        new
                        {
                            TestParametarID = new Guid("75b1dbb5-6b3c-4c76-8044-caff96608e08"),
                            NormalnaVrijednost = "Negativno na maligne stanice"
                        },
                        new
                        {
                            TestParametarID = new Guid("84bfaf38-20b5-4648-b8f0-9d2c4cf7b95a"),
                            NormalnaVrijednost = "Negativno na MRSA"
                        },
                        new
                        {
                            TestParametarID = new Guid("e16fecb2-a4cf-41fd-a264-18dbc8a25cc8"),
                            Jedinica = "mg/L",
                            MaxVrijednost = 30f,
                            MinVrijednost = 0f
                        });
                });

            modelBuilder.Entity("MedLabO.Services.Database.Usluga", b =>
                {
                    b.Property<int>("UslugaID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UslugaID"), 1L, 1);

                    b.Property<Guid?>("AdministratorID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("Cijena")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("DTKreiranja")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DTZadnjeModifikacije")
                        .HasColumnType("datetime2");

                    b.Property<bool>("Dostupno")
                        .HasColumnType("bit");

                    b.Property<string>("Naziv")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Opis")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<float>("RezultatUH")
                        .HasColumnType("real");

                    b.Property<byte[]>("Slika")
                        .HasColumnType("varbinary(max)");

                    b.Property<int>("TrajanjeUMin")
                        .HasColumnType("int");

                    b.HasKey("UslugaID");

                    b.HasIndex("AdministratorID");

                    b.ToTable("Usluge");

                    b.HasData(
                        new
                        {
                            UslugaID = 1,
                            AdministratorID = new Guid("e6bb3c49-9aa6-4ef0-9625-b16bb3775e58"),
                            Cijena = 6m,
                            DTKreiranja = new DateTime(2023, 12, 17, 0, 4, 29, 273, DateTimeKind.Local).AddTicks(5653),
                            Dostupno = true,
                            Naziv = "Krvna slika",
                            Opis = "Mjerenje osnovnih testova vezanih za krvnu sliku.",
                            RezultatUH = 24f,
                            TrajanjeUMin = 10
                        },
                        new
                        {
                            UslugaID = 2,
                            AdministratorID = new Guid("e6bb3c49-9aa6-4ef0-9625-b16bb3775e58"),
                            Cijena = 8m,
                            DTKreiranja = new DateTime(2023, 12, 17, 0, 4, 29, 273, DateTimeKind.Local).AddTicks(5712),
                            Dostupno = true,
                            Naziv = "Jetreni panel",
                            Opis = "Kompletna analiza funkcije jetre.",
                            RezultatUH = 24f,
                            TrajanjeUMin = 15
                        },
                        new
                        {
                            UslugaID = 3,
                            AdministratorID = new Guid("e6bb3c49-9aa6-4ef0-9625-b16bb3775e58"),
                            Cijena = 4m,
                            DTKreiranja = new DateTime(2023, 12, 17, 0, 4, 29, 273, DateTimeKind.Local).AddTicks(5752),
                            Dostupno = true,
                            Naziv = "Kardiovaskularni rizik",
                            Opis = "Procjena rizika od kardiovaskularnih bolesti.",
                            RezultatUH = 24f,
                            TrajanjeUMin = 10
                        },
                        new
                        {
                            UslugaID = 4,
                            AdministratorID = new Guid("e6bb3c49-9aa6-4ef0-9625-b16bb3775e58"),
                            Cijena = 5m,
                            DTKreiranja = new DateTime(2023, 12, 17, 0, 4, 29, 273, DateTimeKind.Local).AddTicks(5778),
                            Dostupno = true,
                            Naziv = "Upalni marker",
                            Opis = "Testiranje za otkrivanje upalnih procesa u tijelu.",
                            RezultatUH = 24f,
                            TrajanjeUMin = 10
                        },
                        new
                        {
                            UslugaID = 5,
                            AdministratorID = new Guid("e6bb3c49-9aa6-4ef0-9625-b16bb3775e58"),
                            Cijena = 4m,
                            DTKreiranja = new DateTime(2023, 12, 17, 0, 4, 29, 273, DateTimeKind.Local).AddTicks(5799),
                            Dostupno = true,
                            Naziv = "Bubrežni panel",
                            Opis = "Procjena funkcije bubrega i rizika od dijabetesa.",
                            RezultatUH = 24f,
                            TrajanjeUMin = 15
                        },
                        new
                        {
                            UslugaID = 6,
                            AdministratorID = new Guid("e6bb3c49-9aa6-4ef0-9625-b16bb3775e58"),
                            Cijena = 9m,
                            DTKreiranja = new DateTime(2023, 12, 17, 0, 4, 29, 273, DateTimeKind.Local).AddTicks(5813),
                            Dostupno = true,
                            Naziv = "Respiratorni panel",
                            Opis = "Analiza respiratornog sistema za otkrivanje infekcija.",
                            RezultatUH = 48f,
                            TrajanjeUMin = 20
                        });
                });

            modelBuilder.Entity("MedLabO.Services.Database.Zakljucak", b =>
                {
                    b.Property<Guid>("ZakljucakID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Detaljno")
                        .IsRequired()
                        .HasMaxLength(10000)
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Opis")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<Guid?>("TerminID")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("ZakljucakID");

                    b.HasIndex("TerminID");

                    b.ToTable("Zakljucci");
                });

            modelBuilder.Entity("MedLabO.Services.Database.Zvanje", b =>
                {
                    b.Property<int>("ZvanjeID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ZvanjeID"), 1L, 1);

                    b.Property<string>("Naziv")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Opis")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ZvanjeID");

                    b.ToTable("Zvanja");

                    b.HasData(
                        new
                        {
                            ZvanjeID = 1,
                            Naziv = "Ljekar",
                            Opis = "Ljekar u medicinskom laboratoriju specijaliziran je za analizu bioloških uzoraka, dijagnosticiranje bolesti i savjetovanje ostalih zdravstvenih radnika, koristeći naprednu laboratorijsku tehnologiju."
                        },
                        new
                        {
                            ZvanjeID = 2,
                            Naziv = "Laboratorijski tehničar",
                            Opis = "U medicinskom laboratoriju, laboratorijski tehničar precizno izvodi testiranja, održava laboratorijsku opremu i pomaže u interpretaciji rezultata testova."
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("0507e219-2779-4096-8d17-a1a91055dfda"),
                            ConcurrencyStamp = "33bdaece-3b05-4c3d-9e28-6d25aadea48f",
                            Name = "Administrator",
                            NormalizedName = "ADMINISTRATOR"
                        },
                        new
                        {
                            Id = new Guid("6d333ed3-85ff-4863-93cc-76701acb9e52"),
                            ConcurrencyStamp = "3a291db2-ba0f-48fa-bc42-724a7d05ae50",
                            Name = "MedicinskoOsoblje",
                            NormalizedName = "MEDICINSKOOSOBLJE"
                        },
                        new
                        {
                            Id = new Guid("c4f2036e-1b4c-4ac8-836c-f40f09a01a98"),
                            ConcurrencyStamp = "2d1c96f2-34c3-498d-a8f2-c04aab32944a",
                            Name = "Pacijent",
                            NormalizedName = "PACIJENT"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderKey")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);

                    b.HasData(
                        new
                        {
                            UserId = new Guid("e6bb3c49-9aa6-4ef0-9625-b16bb3775e58"),
                            RoleId = new Guid("0507e219-2779-4096-8d17-a1a91055dfda")
                        },
                        new
                        {
                            UserId = new Guid("09098d7d-1be0-4d0b-926d-9eb493d81dcc"),
                            RoleId = new Guid("6d333ed3-85ff-4863-93cc-76701acb9e52")
                        },
                        new
                        {
                            UserId = new Guid("140fb21b-43c9-4da2-86e9-8f99d08d8d28"),
                            RoleId = new Guid("c4f2036e-1b4c-4ac8-836c-f40f09a01a98")
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Name")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("TerminUsluga", b =>
                {
                    b.Property<int>("TerminUslugeUslugaID")
                        .HasColumnType("int");

                    b.Property<Guid>("UslugaTerminiTerminID")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("TerminUslugeUslugaID", "UslugaTerminiTerminID");

                    b.HasIndex("UslugaTerminiTerminID");

                    b.ToTable("TerminUsluga");
                });

            modelBuilder.Entity("TestUsluga", b =>
                {
                    b.Property<int>("TestUslugeUslugaID")
                        .HasColumnType("int");

                    b.Property<Guid>("UslugaTestoviTestID")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("TestUslugeUslugaID", "UslugaTestoviTestID");

                    b.HasIndex("UslugaTestoviTestID");

                    b.ToTable("TestUsluga");
                });

            modelBuilder.Entity("MedLabO.Services.Database.Administrator", b =>
                {
                    b.HasBaseType("MedLabO.Services.Database.ApplicationUser");

                    b.Property<string>("Ime")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsKontakt")
                        .HasColumnType("bit");

                    b.Property<string>("KontaktInfo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Prezime")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasDiscriminator().HasValue("Administrator");

                    b.HasData(
                        new
                        {
                            Id = new Guid("e6bb3c49-9aa6-4ef0-9625-b16bb3775e58"),
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "6fe96a41-e729-4b98-b77e-f3f12d4f5130",
                            Email = "administrator@gmail.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "ADMINISTRATOR@GMAIL.COM",
                            NormalizedUserName = "ADMINISTRATOR",
                            PasswordHash = "AQAAAAEAACcQAAAAEGkOoR+cGiA+ARYPMO/o7JiECUfSxXPCV9IpSjTvFqt8hfAvvj0/2WXjmITiflzgRg==",
                            PhoneNumber = "0601234567",
                            PhoneNumberConfirmed = true,
                            SecurityStamp = "3b110b08-3940-425f-b7bf-cebda20a7605",
                            TwoFactorEnabled = false,
                            UserName = "administrator",
                            isDeleted = false,
                            Ime = "Administrator",
                            IsKontakt = true,
                            KontaktInfo = "administrator@gmail.com",
                            Prezime = "Administrator"
                        });
                });

            modelBuilder.Entity("MedLabO.Services.Database.MedicinskoOsoblje", b =>
                {
                    b.HasBaseType("MedLabO.Services.Database.ApplicationUser");

                    b.Property<DateTime?>("DTPrekidRadnogOdnosa")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DTZaposlenja")
                        .HasColumnType("datetime2");

                    b.Property<string>("Ime")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("MedicinskoOsoblje_Ime");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Prezime")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("MedicinskoOsoblje_Prezime");

                    b.Property<int?>("SpolID")
                        .HasColumnType("int");

                    b.Property<int?>("ZvanjeID")
                        .HasColumnType("int");

                    b.HasIndex("SpolID");

                    b.HasIndex("ZvanjeID");

                    b.HasDiscriminator().HasValue("MedicinskoOsoblje");

                    b.HasData(
                        new
                        {
                            Id = new Guid("09098d7d-1be0-4d0b-926d-9eb493d81dcc"),
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "53f6a720-c8cc-4f6c-a4a4-ef70b73c6bf5",
                            Email = "medicinskoOsoblje@gmail.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "MEDICINSKOOSOBLJE@GMAIL.COM",
                            NormalizedUserName = "MEDICINSKOOSOBLJE",
                            PasswordHash = "AQAAAAEAACcQAAAAEGkOoR+cGiA+ARYPMO/o7JiECUfSxXPCV9IpSjTvFqt8hfAvvj0/2WXjmITiflzgRg==",
                            PhoneNumber = "0607654321",
                            PhoneNumberConfirmed = true,
                            SecurityStamp = "2aa1af3c-765c-4dc4-ac2c-7216939e3f1e",
                            TwoFactorEnabled = false,
                            UserName = "medicinskoOsoblje",
                            isDeleted = false,
                            DTZaposlenja = new DateTime(2020, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Ime = "MedicinskoOsoblje",
                            IsActive = true,
                            Prezime = "MedicinskoOsoblje",
                            SpolID = 2,
                            ZvanjeID = 1
                        });
                });

            modelBuilder.Entity("MedLabO.Services.Database.Pacijent", b =>
                {
                    b.HasBaseType("MedLabO.Services.Database.ApplicationUser");

                    b.Property<string>("Adresa")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DatumRodjenja")
                        .HasColumnType("datetime2");

                    b.Property<string>("Ime")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Pacijent_Ime");

                    b.Property<string>("Prezime")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Pacijent_Prezime");

                    b.Property<int?>("SpolID")
                        .HasColumnType("int")
                        .HasColumnName("Pacijent_SpolID");

                    b.HasIndex("SpolID");

                    b.HasDiscriminator().HasValue("Pacijent");

                    b.HasData(
                        new
                        {
                            Id = new Guid("140fb21b-43c9-4da2-86e9-8f99d08d8d28"),
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "ee1c5d57-e06b-4b35-b200-c80ff2242cbd",
                            Email = "pacijent@gmail.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "PACIJENT@GMAIL.COM",
                            NormalizedUserName = "PACIJENT",
                            PasswordHash = "AQAAAAEAACcQAAAAEGkOoR+cGiA+ARYPMO/o7JiECUfSxXPCV9IpSjTvFqt8hfAvvj0/2WXjmITiflzgRg==",
                            PhoneNumber = "0605555555",
                            PhoneNumberConfirmed = true,
                            SecurityStamp = "7568e1b2-a164-437b-8c85-a232269f08c3",
                            TwoFactorEnabled = false,
                            UserName = "pacijent",
                            isDeleted = false,
                            Adresa = "Ulica Prva 11",
                            DatumRodjenja = new DateTime(1970, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Ime = "Pacijent",
                            Prezime = "Pacijent",
                            SpolID = 1
                        });
                });

            modelBuilder.Entity("MedLabO.Services.Database.Novost", b =>
                {
                    b.HasOne("MedLabO.Services.Database.Administrator", "Administrator")
                        .WithMany("KreiraneNovosti")
                        .HasForeignKey("AdministratorID");

                    b.Navigation("Administrator");
                });

            modelBuilder.Entity("MedLabO.Services.Database.Obavijest", b =>
                {
                    b.HasOne("MedLabO.Services.Database.Administrator", "Administrator")
                        .WithMany("KreiraneObavijesti")
                        .HasForeignKey("AdministratorID");

                    b.Navigation("Administrator");
                });

            modelBuilder.Entity("MedLabO.Services.Database.Racun", b =>
                {
                    b.HasOne("MedLabO.Services.Database.Termin", "Termin")
                        .WithMany()
                        .HasForeignKey("TerminID");

                    b.Navigation("Termin");
                });

            modelBuilder.Entity("MedLabO.Services.Database.Termin", b =>
                {
                    b.HasOne("MedLabO.Services.Database.MedicinskoOsoblje", "MedicinskoOsoblje")
                        .WithMany("OdobreniTermini")
                        .HasForeignKey("MedicinskoOsobljeID");

                    b.HasOne("MedLabO.Services.Database.Pacijent", "Pacijent")
                        .WithMany("Termini")
                        .HasForeignKey("PacijentID");

                    b.HasOne("MedLabO.Services.Database.Racun", "Racun")
                        .WithMany()
                        .HasForeignKey("RacunID");

                    b.HasOne("MedLabO.Services.Database.Zakljucak", "Zakljucak")
                        .WithMany()
                        .HasForeignKey("ZakljucakID");

                    b.Navigation("MedicinskoOsoblje");

                    b.Navigation("Pacijent");

                    b.Navigation("Racun");

                    b.Navigation("Zakljucak");
                });

            modelBuilder.Entity("MedLabO.Services.Database.TerminTest", b =>
                {
                    b.HasOne("MedLabO.Services.Database.Rezultat", "Rezultat")
                        .WithMany()
                        .HasForeignKey("RezultatID");

                    b.HasOne("MedLabO.Services.Database.Termin", "Termin")
                        .WithMany("TerminTestovi")
                        .HasForeignKey("TerminID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MedLabO.Services.Database.Test", "Test")
                        .WithMany("TerminTestovi")
                        .HasForeignKey("TestID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Rezultat");

                    b.Navigation("Termin");

                    b.Navigation("Test");
                });

            modelBuilder.Entity("MedLabO.Services.Database.Test", b =>
                {
                    b.HasOne("MedLabO.Services.Database.Administrator", "Administrator")
                        .WithMany("KreiraniTestovi")
                        .HasForeignKey("AdministratorID");

                    b.HasOne("MedLabO.Services.Database.TestParametar", "TestParametar")
                        .WithMany()
                        .HasForeignKey("TestParametarID");

                    b.Navigation("Administrator");

                    b.Navigation("TestParametar");
                });

            modelBuilder.Entity("MedLabO.Services.Database.Usluga", b =>
                {
                    b.HasOne("MedLabO.Services.Database.Administrator", null)
                        .WithMany("KreiraneUsluge")
                        .HasForeignKey("AdministratorID");
                });

            modelBuilder.Entity("MedLabO.Services.Database.Zakljucak", b =>
                {
                    b.HasOne("MedLabO.Services.Database.Termin", "Termin")
                        .WithMany()
                        .HasForeignKey("TerminID");

                    b.Navigation("Termin");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.HasOne("MedLabO.Services.Database.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.HasOne("MedLabO.Services.Database.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MedLabO.Services.Database.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.HasOne("MedLabO.Services.Database.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("TerminUsluga", b =>
                {
                    b.HasOne("MedLabO.Services.Database.Usluga", null)
                        .WithMany()
                        .HasForeignKey("TerminUslugeUslugaID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MedLabO.Services.Database.Termin", null)
                        .WithMany()
                        .HasForeignKey("UslugaTerminiTerminID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("TestUsluga", b =>
                {
                    b.HasOne("MedLabO.Services.Database.Usluga", null)
                        .WithMany()
                        .HasForeignKey("TestUslugeUslugaID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MedLabO.Services.Database.Test", null)
                        .WithMany()
                        .HasForeignKey("UslugaTestoviTestID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MedLabO.Services.Database.MedicinskoOsoblje", b =>
                {
                    b.HasOne("MedLabO.Services.Database.Spol", "Spol")
                        .WithMany()
                        .HasForeignKey("SpolID");

                    b.HasOne("MedLabO.Services.Database.Zvanje", "Zvanje")
                        .WithMany("MedicinskoOsoblje")
                        .HasForeignKey("ZvanjeID");

                    b.Navigation("Spol");

                    b.Navigation("Zvanje");
                });

            modelBuilder.Entity("MedLabO.Services.Database.Pacijent", b =>
                {
                    b.HasOne("MedLabO.Services.Database.Spol", "Spol")
                        .WithMany()
                        .HasForeignKey("SpolID");

                    b.Navigation("Spol");
                });

            modelBuilder.Entity("MedLabO.Services.Database.Termin", b =>
                {
                    b.Navigation("TerminTestovi");
                });

            modelBuilder.Entity("MedLabO.Services.Database.Test", b =>
                {
                    b.Navigation("TerminTestovi");
                });

            modelBuilder.Entity("MedLabO.Services.Database.Zvanje", b =>
                {
                    b.Navigation("MedicinskoOsoblje");
                });

            modelBuilder.Entity("MedLabO.Services.Database.Administrator", b =>
                {
                    b.Navigation("KreiraneNovosti");

                    b.Navigation("KreiraneObavijesti");

                    b.Navigation("KreiraneUsluge");

                    b.Navigation("KreiraniTestovi");
                });

            modelBuilder.Entity("MedLabO.Services.Database.MedicinskoOsoblje", b =>
                {
                    b.Navigation("OdobreniTermini");
                });

            modelBuilder.Entity("MedLabO.Services.Database.Pacijent", b =>
                {
                    b.Navigation("Termini");
                });
#pragma warning restore 612, 618
        }
    }
}
